### ISSUE TITLE
Pages for languages other than English is outdated

### ISSUE THREAD

**Issue by KagamiChan** [Nya-chan/k2badge#14]
Hi, it seems that pages for other languages are reverted to an earlier version, is this intended?

![image](https://user-images.githubusercontent.com/3816900/27178094-7639a042-51fb-11e7-8342-027d62c5321e.png)

**Comment by Nya-chan** [comment]
They are not reverted, they have never been updated - we don't have people with proper Japanese skills to update the foreign versions, basically.

**Comment by KagamiChan** [comment]
Thank you for your explaination. So do you have any plan for multi-language support/hosting? and what actions should be done to keep them up to date with English version / game data? This information will be of help for potential contributors (not me for now, though).

**Comment by Nya-chan** [comment]
Support and hosting is still both available. To update the game data, the only thing necessary is to fork this repo and update dbj.json and sb2j.json, I think. The rest is largely automatically tied to English version and if there are issues they can be solved fast when these files are updated.
