### ISSUE TITLE
Issues from badge export from KC3Kai

### ISSUE THREAD

**Issue by Doppelsoldner** [Nya-chan/k2badge#23]
Some ships are not being detected when exported from KC3Kai. Already cleaned cache and cookies.

Not detected in kai 2 screen: Saratoga Mk. II Mod 2.

Base models not detected from remodels in poster screen: Saratoga Mk. II Mod 2., I-504

Also, not sure if it was an oversight, but Luigi's remodels were left out of the kai 2 screen, and currently only Ro-500 is in the SS category.

**Comment by Nya-chan** [comment]
Adding one more to this - Matsuwa seems to be absent from the poster list, overlooked her, since she was at the top.

**Comment by Tibo442** [comment]
Saratoga Mk. II is missing as well (non mod2)

**Comment by Nya-chan** [comment]
Should be solved, hopefully
