### ISSUE TITLE
Matsuwa is missing

### ISSUE THREAD

**Issue by DynamicSTOP** [Nya-chan/k2badge#24]
master id 525
![default](https://user-images.githubusercontent.com/9434504/30525905-8646b84e-9c10-11e7-8ff6-4d16d100462b.png)
![default](https://user-images.githubusercontent.com/9434504/30525906-900f0c3c-9c10-11e7-88df-1e91a5df76ad.png)

**Comment by Nya-chan** [comment]
Also mentioned in #23

**Comment by DynamicSTOP** [comment]
well... i missed that message. sumimasen
