### ISSUE TITLE
Musasi Kai Ni not showing up under BB

### ISSUE THREAD

**Issue by Jasper1224** [Nya-chan/k2badge#40]
Musashi probably does show up, but I can't check, all I know is Musashi Kai Ni is not showing up in the list, I know what ships I'm missing in the battleship fleet, so it was confusing as to why I was missing three instead of two.
Screenshot: https://imgur.com/a/mlYsX

**Comment by Nya-chan** [comment]
This should now be fixed with the latest updates.
