### ISSUE TITLE
Kuroshio Kai-Ni appears in the Poster Collection Tab.

### ISSUE THREAD

**Issue by Inazumattk** [Nya-chan/k2badge#49]
![image](https://user-images.githubusercontent.com/44546043/47615678-2c4ebb00-daf5-11e8-86e8-23b9c72aebe5.png)

**Comment by HarvestasyaNT** [comment]
Oh, you're right. I had updated all the fields in her kai-ni but missed the uniqueness

**Comment by HarvestasyaNT** [comment]
fixed in #48
