### ISSUE TITLE
Remodels not being recognized

### ISSUE THREAD

**Issue by Grunilg** [Nya-chan/k2badge#59]
On a full Kandex, the following Ships don't seem to be showing up on the "Poster" option:

- Hirato Kai, Hyuuga K2, Nisshin A, Shikinami K2, Asashimo K2

In the "Kai 2" tab, the following ship doesn't seem to show up:

- Yuubari Kai Ni Toku

**Comment by HarvestasyaNT** [comment]
So, it looks like I forgot Hirato Kai, Nisshin A was spelled wrong, Shikinami K2 and  Asashimo K2 were given the wrong keys, completely forgot how the conversions worked with Yuubari, and copy-pasta'd Ise K2 entry for Hyuuga
